dist: bionic

language: generic

services: docker

script:
  - sudo apt update -y && sudo apt install -y wget curl jq unzip ffmpeg fftw3
  - chmod +x download_inspector.sh
  - ./download_inspector.sh
  - chmod +x gen_pitches.sh
  - chmod +x pitch_detector
    # TODO: move to before_before deploy. Now inspector fails if there are no *.pitch files in courses
  - ./gen_pitches.sh StudyIntonation
  - ./gen_pitches.sh CrashCourse
  - unzip inspector.zip
  - docker run -v $TRAVIS_BUILD_DIR:/prof-courses lamtev/java:latest /bin/bash -c " cd prof-courses && ./inspector/bin/inspector CrashCourse && ./inspector/bin/inspector StudyIntonation "

before_deploy:
  - docker run -v $TRAVIS_BUILD_DIR:/prof-courses lamtev/java:latest /bin/bash -c " cd prof-courses && ./inspector/bin/inspector -info . $TRAVIS_TAG "
  - chmod 777 ${TRAVIS_BUILD_DIR}/info.json
  - chmod 777 ${TRAVIS_BUILD_DIR}/CrashCourse.zip
  - chmod 777 ${TRAVIS_BUILD_DIR}/StudyIntonation.zip
  
deploy:
  provider: releases 
  api_key: "$GITHUB_DEPLOY_TOKEN" 
  file: 
    - ${TRAVIS_BUILD_DIR}/info.json
    - ${TRAVIS_BUILD_DIR}/CrashCourse.zip
    - ${TRAVIS_BUILD_DIR}/StudyIntonation.zip
  skip_cleanup: true 
  on: 
    tags: true

